%YAML:1.0 # need to specify the file type at the top!

imu0:
  T_i_b:
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
#  accelerometer_noise_density: 0.00333388 # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
#  accelerometer_random_walk: 0.00047402   # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
#  gyroscope_noise_density: 0.00005770     # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
#  gyroscope_random_walk: 0.00001565       # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
#  accelerometer_noise_density: 0.00186   # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
#  accelerometer_random_walk: 0.006   # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
#  gyroscope_noise_density: 0.00018665      # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
#  gyroscope_random_walk: 3.8785e-05      # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  accelerometer_noise_density: 0.00002   # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accelerometer_random_walk: 0.0000002   # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  gyroscope_noise_density: 0.000006      # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyroscope_random_walk: 0.00000003       # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
#  accelerometer_noise_density: 0.0   # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
#  accelerometer_random_walk: 0.0   # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
#  gyroscope_noise_density: 0.0      # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
#  gyroscope_random_walk: 0.0       # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )

  rostopic: /mavros/imu/data
  time_offset: 0.0
  update_rate: 250.0
  # three different modes supported:
  # "calibrated" (same as "kalibr"), "kalibr", "rpng"
  model: "kalibr"
  # how to get from Kalibr imu.yaml result file:
  #   - Tw is imu0:gyroscopes:M:
  #   - R_IMUtoGYRO: is imu0:gyroscopes:C_gyro_i:
  #   - Ta is imu0:accelerometers:M:
  #   - R_IMUtoACC not used by Kalibr
  #   - Tg is imu0:gyroscopes:A:
  Tw:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  R_IMUtoGYRO:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  Ta:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  R_IMUtoACC:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  Tg:
    - [ 0.0, 0.0, 0.0 ]
    - [ 0.0, 0.0, 0.0 ]
    - [ 0.0, 0.0, 0.0 ]